# All selected in one module named smsmdtv
#gps-objs                   := gpsdriver.o PALAPI.o gpsdrv.a
#obj-$(CONFIG_GPS_RK)		+= gps.o

gps-objs                   := rk_gps_null.o
obj-$(CONFIG_GPS_RK)		+= gps.o
